# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"o\n\x0bVectorClock\x12\x32\n\x05\x63lock\x18\x01 \x03(\x0b\x32#.suggestions.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"5\n\x04\x42ook\x12\x0e\n\x06\x62ookid\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"W\n\x15getSuggestionsRequest\x12\x0e\n\x06\x62ookid\x18\x01 \x01(\t\x12.\n\x0cvector_clock\x18\x02 \x01(\x0b\x32\x18.suggestions.VectorClock\"g\n\x13SuggestionsResponse\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.suggestions.Book\x12.\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x18.suggestions.VectorClock2l\n\x12SuggestionsService\x12V\n\x0egetSuggestions\x12\".suggestions.getSuggestionsRequest\x1a .suggestions.SuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCK']._serialized_start=34
  _globals['_VECTORCLOCK']._serialized_end=145
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=101
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=145
  _globals['_BOOK']._serialized_start=147
  _globals['_BOOK']._serialized_end=200
  _globals['_GETSUGGESTIONSREQUEST']._serialized_start=202
  _globals['_GETSUGGESTIONSREQUEST']._serialized_end=289
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=291
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=394
  _globals['_SUGGESTIONSSERVICE']._serialized_start=396
  _globals['_SUGGESTIONSSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
