# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0cverification\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\xa8\x01\n\x0bTransaction\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.verification.Item\x12 \n\x04user\x18\x02 \x01(\x0b\x32\x12.verification.User\x12-\n\x0b\x63redit_card\x18\x03 \x01(\x0b\x32\x18.verification.CreditCard\x12%\n\x1dterms_and_conditions_accepted\x18\x04 \x01(\x08\"J\n\x18VerifyTransactionRequest\x12.\n\x0btransaction\x18\x01 \x01(\x0b\x32\x19.verification.Transaction\"D\n\x19VerifyTransactionResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x86\x01\n\x1eTransactionVerificationService\x12\x64\n\x11VerifyTransaction\x12&.verification.VerifyTransactionRequest\x1a\'.verification.VerifyTransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=48
  _globals['_USER']._serialized_end=85
  _globals['_CREDITCARD']._serialized_start=87
  _globals['_CREDITCARD']._serialized_end=152
  _globals['_ITEM']._serialized_start=154
  _globals['_ITEM']._serialized_end=192
  _globals['_TRANSACTION']._serialized_start=195
  _globals['_TRANSACTION']._serialized_end=363
  _globals['_VERIFYTRANSACTIONREQUEST']._serialized_start=365
  _globals['_VERIFYTRANSACTIONREQUEST']._serialized_end=439
  _globals['_VERIFYTRANSACTIONRESPONSE']._serialized_start=441
  _globals['_VERIFYTRANSACTIONRESPONSE']._serialized_end=509
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=512
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)