# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"s\n\x0bVectorClock\x12\x36\n\x05\x63lock\x18\x01 \x03(\x0b\x32\'.fraud_detection.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"U\n\x0c\x46raudRequest\x12\x11\n\ttotal_qty\x18\x01 \x01(\x05\x12\x32\n\x0cvector_clock\x18\x02 \x01(\x0b\x32\x1c.fraud_detection.VectorClock\"f\n\rFraudResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x32\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x1c.fraud_detection.VectorClock2h\n\x15\x46raudDetectionService\x12O\n\x0e\x46raudDetection\x12\x1d.fraud_detection.FraudRequest\x1a\x1e.fraud_detection.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCK']._serialized_start=42
  _globals['_VECTORCLOCK']._serialized_end=157
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=113
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=157
  _globals['_FRAUDREQUEST']._serialized_start=159
  _globals['_FRAUDREQUEST']._serialized_end=244
  _globals['_FRAUDRESPONSE']._serialized_start=246
  _globals['_FRAUDRESPONSE']._serialized_end=348
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=350
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
